system:
  env: public
  port: 8818
  router-prefix: "" # 路由前缀

zap:
  level: info
  prefix: '[chat-api-reverse]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true

copilot:
  # github copilot
  tokenUrl: https://api.github.com/copilot_internal/v2/token
  copilotHost: api.github.com
  completionsUrl: https://api.githubcopilot.com/chat/completions

  # cocopilot
  coCopilotHost: api.cocopilot.org
  coTokenUrl: https://api.cocopilot.org/copilot_internal/v2/token

openai:
  baseUrl: https://chat.fungs.cn/proxy520


